export const agentInftAbi = [
  {
    type: "function",
    name: "mintClan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "clanName", type: "string" },
      { name: "archetype", type: "string" },
      { name: "modelType", type: "string" },
      { name: "metadataHash", type: "bytes32" },
      { name: "storageURI", type: "string" },
      { name: "memoryRootURI", type: "string" },
      { name: "realmRootURI", type: "string" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "updateRealmRoot",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newRealmRootURI", type: "string" },
      { name: "newRealmCount", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateVoteRoot",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newVoteRootURI", type: "string" },
      { name: "newProposalCount", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordClanEvolution",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newMetadataHash", type: "bytes32" },
      { name: "newStorageURI", type: "string" },
      { name: "newMemoryRootURI", type: "string" },
      { name: "newRealmRootURI", type: "string" },
      { name: "newMemorySize", type: "uint256" },
      { name: "newRealmCount", type: "uint256" },
      { name: "proof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "listForSale",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "price", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "delist",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getClanState",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "memoryRootURI", type: "string" },
          { name: "realmRootURI", type: "string" },
          { name: "voteRootURI", type: "string" },
          { name: "realmCount", type: "uint256" },
          { name: "proposalCount", type: "uint256" },
          { name: "evolutionCount", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenOfOwnerByIndex",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "ClanMinted",
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "clanName", type: "string" },
      { indexed: false, name: "memoryRootURI", type: "string" },
    ],
  },
] as const;
